sudo: required
services: 
  - docker
before_install:
  - docker build -t zoltot1/react-test  -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true zoltot1/react-test npm test

after_success: 
  - docker build -t zoltot1/multi-client ./client
  - docker build -t zoltot1/multi-nginx ./nginx
  - docker build -t zoltot1/multi-server ./server
  - docker build -t zoltot1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zoltot1/multi-client
  - docker push  zoltot1/multi-nginx
  - docker push zoltot1/multi-server
  - docker push zoltot1/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289qqq'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

